server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedlr
    username: root
    password: passw0rd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        ddl-auto: update
    show-sql: true
  main:
    web-application-type: servlet